### ISSUE TITLE
mybatis-plus 3.5.6下，xml热加载无效了

### ISSUE THREAD

**Issue by yhl452493373** [SweetInk/jrebel-mybatisplus-idea-plugin#10]
## mybatis-plus 3.5.6下，xml热加载无效了。。
+ mybatis-plus 3.5.5下，试过idea2023.3+jrebel2023.4，idea2023.3+jrebel2024.2，idea2024.1+jrebel2024.2，xml都正常热加载
+ mybatis-plus 3.5.6下，idea2023.3+jrebel2023.4，idea2023.3+jrebel2024.2，idea2024.1+jrebel2024.2，都无法热加载xml

**Comment by SweetInk** [comment]
原因是由于mp的某次改动 [Json处理器支持自定义XML.](https://github.com/baomidou/mybatis-plus/commit/2381495af9c4e2d368b2d86a973ffb0bcc86aade#diff-b8cf8a5022a9a425d79ce7e243277c69002d4f0c387a1f047dd83b06e9f4ac5eR167)

**Comment by yhl452493373** [comment]
> 原因是由于mp的某次改动 [Json处理器支持自定义XML.](https://github.com/baomidou/mybatis-plus/commit/2381495af9c4e2d368b2d86a973ffb0bcc86aade#diff-b8cf8a5022a9a425d79ce7e243277c69002d4f0c387a1f047dd83b06e9f4ac5eR167)

感谢。自己编译了下，通过改插件字节码的方式，在3.5.6能用了。不过市场插件没更新，不知道啥时候能更新下市场？

**Comment by SweetInk** [comment]
> > 原因是由于mp的某次改动 [Json处理器支持自定义XML.](https://github.com/baomidou/mybatis-plus/commit/2381495af9c4e2d368b2d86a973ffb0bcc86aade#diff-b8cf8a5022a9a425d79ce7e243277c69002d4f0c387a1f047dd83b06e9f4ac5eR167)
> 
> 感谢。自己编译了下，通过改插件字节码的方式，在3.5.6能用了。不过市场插件没更新，不知道啥时候能更新下市场？

插件上传市场了，还在审核中...

**Comment by SweetInk** [comment]
插件审核通过了，你可以试试

> > 原因是由于mp的某次改动 [Json处理器支持自定义XML.](https://github.com/baomidou/mybatis-plus/commit/2381495af9c4e2d368b2d86a973ffb0bcc86aade#diff-b8cf8a5022a9a425d79ce7e243277c69002d4f0c387a1f047dd83b06e9f4ac5eR167)
> 
> 感谢。自己编译了下，通过改插件字节码的方式，在3.5.6能用了。不过市场插件没更新，不知道啥时候能更新下市场？

**Comment by yhl452493373** [comment]
多谢
