### ISSUE TITLE
mapper.xml无法热部署

### ISSUE THREAD

**Issue by sa-yuki** [SweetInk/jrebel-mybatisplus-idea-plugin#3]
spring-boot - 2.3.4.RELEASE
mybatis-plus-boot-starter - 3.4.2

安装了JRebel和JRebel mybatisPlus extension插件

class正常热部署,mapper.xml无法热部署,需要重新编译

**Comment by SweetInk** [comment]
我测试了可以热部署
你启动项目有如下日志输出吗

```
JRebel: Ready config JRebel MybatisPlus plugin...
JRebel: Add CBP for mybatis-plus core classes...
```

**Comment by sa-yuki** [comment]
> 我测试了可以热部署 你启动项目有如下日志输出吗
> 
> ```
> JRebel: Ready config JRebel MybatisPlus plugin...
> JRebel: Add CBP for mybatis-plus core classes...
> ```

有的，但是多一个添加特殊CBPs的提示

JRebel: Ready config JRebel MybatisPlus plugin...
JRebel: Add CBP for mybatis-plus core classes...
JRebel: Detected mybatis-plus version is v3.4.0+, add special CBPs...

**Comment by SweetInk** [comment]
改了mapper.xml后重新请求接口有没有输出这个`JRebel: Reloading SQL maps`

**Comment by SweetInk** [comment]
看看你的Configuration![image](https://user-images.githubusercontent.com/8621607/158552446-3963551c-386a-4bd2-86cb-3bc921daafcd.png)

**Comment by sa-yuki** [comment]
> 改了mapper.xml后重新请求接口有没有输出这个`JRebel: Reloading SQL maps`

没有输出这个

**Comment by sa-yuki** [comment]
> 看看你的Configuration![image](https://user-images.githubusercontent.com/8621607/158552446-3963551c-386a-4bd2-86cb-3bc921daafcd.png)

![image](https://user-images.githubusercontent.com/53472887/158552837-3ebcdb4f-0db9-4873-8498-ac8767ec45ec.png)
我的Configurations貌似和你的不一样

**Comment by SweetInk** [comment]
你改了xml后可以试试CTRL+SHIFT+F9，

**Comment by SweetInk** [comment]
我用的IDEA 2021.2.4版本

**Comment by sa-yuki** [comment]
> 你改了xml后可以试试CTRL+SHIFT+F9，

改了XML之后按CTRL+SHIFT+F9会提示Loaded classes are up to date. Nothing to reload.

**Comment by sa-yuki** [comment]
> 我用的IDEA 2021.2.4版本

我的是2021.3.2版本

**Comment by SweetInk** [comment]
> > 你改了xml后可以试试CTRL+SHIFT+F9，
> 
> 改了XML之后按CTRL+SHIFT+F9会提示Loaded classes are up to date. Nothing to reload.

在xml编辑窗口的左下角应该有这个提示`File 'testMapper.xml' has been packaged at 4:59:20 下午.`

**Comment by sa-yuki** [comment]
> 

我这边并没有这个提示，我换和你一个版本的IDEA试试

**Comment by sa-yuki** [comment]
![image](https://user-images.githubusercontent.com/53472887/158554817-28ba1597-7caa-47e0-8e64-803870d78bdb.png)
看样子是IDEA新版本移除了Configuration中的Spring Boot配置

**Comment by sa-yuki** [comment]
已经修改了Configuration，还是无法热部署，左下角一直提示Loaded classes are up to date. Nothing to reload.

**Comment by SweetInk** [comment]
On 'Update' action: Update classes and resources

**Comment by sa-yuki** [comment]
> On 'Update' action: Update classes and resources

![image](https://user-images.githubusercontent.com/53472887/158562209-989073c0-711b-4097-9af6-bb7083174352.png)
配置了这个，修改xml后按CTRL+SHIFT+F9提示Loaded classes are up to date. Nothing to reload.

**Comment by SweetInk** [comment]
![image](https://user-images.githubusercontent.com/8621607/158563265-3c8484c1-f2a4-4a01-ae84-f8f8c2c4916d.png)

理论上你改了xml后，你的project/target 下会有最新修改后的xml,JRebel扫描的文件也是这个目录下的

**Comment by sa-yuki** [comment]
![Desktop Screenshot 2022 03 16 - 17 51 41 89](https://user-images.githubusercontent.com/53472887/158563437-9bbaf579-afbf-46d1-b38e-0932dd1ecefa.png)
我这边target下的xml并没有被更新

**Comment by sa-yuki** [comment]
方便发一下你的测试项目吗，我看看是否有配置上的不同

**Comment by SweetInk** [comment]
> 方便发一下你的测试项目吗，我看看是否有配置上的不同

https://wwb.lanzoub.com/iScU901jymcj

**Comment by sa-yuki** [comment]
> > 方便发一下你的测试项目吗，我看看是否有配置上的不同
> 
> https://wwb.lanzoub.com/iScU901jymcj

我这边mapper文件没有放在resources下，是这个问题吗

**Comment by sa-yuki** [comment]
我的mapper是放在mapper/xml下的
![image](https://user-images.githubusercontent.com/53472887/158580291-1001afbd-149e-4452-ac53-7cb1dd8ba95f.png)

**Comment by sa-yuki** [comment]
![image](https://user-images.githubusercontent.com/53472887/158581902-59b06f09-838d-4d54-b452-4fa4c62dae0c.png)
我把mapper放到resources下就可以热部署了，在mapper/xml下有办法热部署吗

**Comment by SweetInk** [comment]
> 

你指的是`src/main/java`下的`mapper package`吗，如果是的话，尝试在你的`pom.xml`里添加如下代码

```xml
 <build>
        <resources>
            <resource>
                <directory>src/main/java</directory>
                <includes>
                    <include>**/*.xml</include>
                </includes>
            </resource>
        </resources>
    </build>
```

**Comment by sa-yuki** [comment]
> > 
> 
> 你指的是`src/main/java`下的`mapper package`吗，如果是的话，尝试在你的`pom.xml`里添加如下代码
> 
> ```
>  <build>
>         <resources>
>             <resource>
>                 <directory>src/main/java</directory>
>                 <includes>
>                     <include>**/*.xml</include>
>                 </includes>
>             </resource>
>         </resources>
>     </build>
> ```

感谢，可以正常热部署了
